services:
  app:
    build: .
    command: sh -c "uv run alembic upgrade head && uv run uvicorn src.main:app --host=0.0.0.0 --port 8080 --workers 4"
    container_name: app
    volumes:
      - .env:/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - network

  postgres:
    image: postgres:17.4
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${CONFIG__DATABASE__PASSWORD:-password}
      POSTGRES_USER: ${CONFIG__DATABASE__USER:-user}
      POSTGRES_DB: ${CONFIG__DATABASE__DATABASE:-database}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CONFIG__DATABASE__USER:-user} -d ${CONFIG__DATABASE__DATABASE:-database}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  postgres_data:

networks:
  network:
    driver: bridge