[project]
name = "shorter"
version = "0.1.0"
description = " FastAPI service for shortening links "
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.2",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.116.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]
