import uuid

from sqlalchemy import DateTime, func, UUID, text
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column


class IdPkMixin:
    """
    Mixin that adds UUID primary key column to models.

    Provides:
        id: UUID primary key (server-generated by default)
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()")
    )


class CreatedAtMixin:
    """
    Mixin that adds creation timestamp to models.

    Provides:
        created_at: DateTime set automatically on creation
    """

    created_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )


class LastUpdatedAtMixin:
    """Mixin that adds auto-updating timestamp to models.

    Provides:
        last_updated_at: DateTime updated automatically on changes
    """

    last_updated_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )


__all__ = ["IdPkMixin", "CreatedAtMixin", "LastUpdatedAtMixin"]
